import 'controller/t_i_kho_n_h_y_controller.dart';import 'package:flutter/material.dart';import 'package:quang_nam_travel/core/app_export.dart';import 'package:quang_nam_travel/widgets/custom_button.dart';import 'package:quang_nam_travel/widgets/custom_icon_button.dart';
// ignore_for_file: must_be_immutable
class TIKhoNHYBottomsheet extends StatelessWidget {TIKhoNHYBottomsheet(this.controller);

TIKhoNHYController controller;

@override Widget build(BuildContext context) { return SingleChildScrollView(child: Container(width: double.infinity, decoration: AppDecoration.fillWhiteA700.copyWith(borderRadius: BorderRadiusStyle.customBorderTL20), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.center, mainAxisAlignment: MainAxisAlignment.end, children: [CustomIconButton(height: 60, width: 60, margin: getMargin(left: 51, top: 20, right: 51), variant: IconButtonVariant.FillDeeporange50, shape: IconButtonShape.CircleBorder30, child: CommonImageView(svgPath: ImageConstant.imgUser1)), Padding(padding: getPadding(left: 51, top: 16, right: 51), child: Text("lbl_h_y_t_i_kho_n".tr.toUpperCase(), overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtMulishRomanSemiBold20)), Container(width: getHorizontalSize(268.00), margin: getMargin(left: 51, top: 22, right: 51), child: Text("msg_b_n_kh_ng_s_d_ng".tr, maxLines: null, textAlign: TextAlign.left, style: AppStyle.txtMulishRomanMedium16Bluegray800.copyWith(height: 1.38))), GestureDetector(onTap: () {onTapRowng();}, child: Padding(padding: getPadding(left: 51, top: 29, right: 51), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.center, mainAxisSize: MainAxisSize.max, children: [CustomButton(width: 125, text: "lbl_ng".tr.toUpperCase(), shape: ButtonShape.CircleBorder18, fontStyle: ButtonFontStyle.MulishRomanSemiBold14), CustomButton(width: 125, text: "lbl_h_y".tr.toUpperCase(), margin: getMargin(left: 17), variant: ButtonVariant.FillBluegray200, shape: ButtonShape.CircleBorder18, padding: ButtonPadding.PaddingAll7, fontStyle: ButtonFontStyle.MulishRomanSemiBold14)]))), Container(height: getVerticalSize(5.00), width: getHorizontalSize(137.00), margin: getMargin(left: 51, top: 29, right: 51, bottom: 8), decoration: BoxDecoration(color: ColorConstant.black900, borderRadius: BorderRadius.circular(getHorizontalSize(2.58))))]))); } 
onTapRowng() { Get.toNamed(AppRoutes.tIKhoNScreen); } 
 }
